name: firebase_auth_vm
description: Dart implementation of Firebase Auth SDK that offers secure End-To-End Authentication
version: 0.1.0
homepage: https://github.com/long1eu/firebase_sdk/tree/main/packages/firebase_auth/firebase_auth_vm
commit: 8843dbfd25aa8e99c5cb960cdaea12fc9598cee0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  _discoveryapis_commons: ^1.0.2
  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0
  http: ^0.13.3
  firebase: ^9.0.2
  rxdart: ^0.27.2

  _firebase_internal_vm: #^0.0.2+1
    path: ../../firebase_core/_firebase_internal_vm
  firebase_core_vm: #^0.0.8
    path: ../../firebase_core/firebase_core_vm
