name: firebase_auth_vm_example
description: Example app for firebase_auth_vm

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.12
  uuid: ^3.0.4
  hive: ^2.0.4
  firebase_dynamic_links: ^2.0.10
  google_sign_in: ^5.1.1
  google_sign_in_dartio: ^0.1.0

  firebase_platform_dependencies: #^0.0.1+1
    path: ../../../firebase_core/firebase_platform_dependencies
  firebase_auth_vm:
    path: ../

flutter:
  uses-material-design: true
