name: _firebase_internal_vm
description: For internal use of the Firebase packages
version: 0.1.0+1
homepage: https://github.com/long1eu/firebase_sdk/tree/main/packages/firebase_core/_firebase_internal_vm

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0