name: firebase_auth_dart_example
description: Example app for firebase_auth_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_dynamic_links: ^0.6.0

  google_sign_in: ^4.5.3
  google_sign_in_dartio: ^0.0.8
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  rxdart: ^0.24.1
  flutter_signin_button: ^1.1.0
  firebase_core_dart: ^0.0.5
  firebase_auth_dart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true