name: firebase_platform_dependencies
description: Flutter implementation of the PlatformDependencies required by FirebaseApp
version: 0.1.0
repository: https://github.com/long1eu/firebase_sdk/tree/main/packages/firebase_core/firebase_platform_dependencies

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core_vm: # ^0.0.7
    path: ../firebase_core_vm

  path_provider: ^2.0.5
  connectivity_plus: ^1.2.0
  hive: ^2.0.4
  rxdart: ^0.27.2