name: firebase_core_dart_example
description: Example app for firebase_core_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  pedantic: ^1.11.1

  firebase_core: ^1.7.0
  firebase_core_dart:
    path: ../

flutter:
  uses-material-design: true