name: firebase_auth_vm_example
description: Example app for firebase_auth_vm

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_sign_in: ^4.5.3
  google_sign_in_dartio: ^0.0.8
  url_launcher: ^5.5.2
  uuid: ^2.2.2
  hive: ^1.4.4
  firebase_dynamic_links: ^0.6.0

  firebase_platform_dependencies: ^0.0.1+1
  firebase_auth_vm:
    path: ../../

dev_dependencies:
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
