name: firebase_core_vm
description: Dart implementation of Firebase Core SDK that provides FirebaseApps used by all Firebase services
version: 0.1.0
homepage: https://github.com/long1eu/firebase_sdk/tree/main/packages/firebase_core/firebase_core_vm

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  _firebase_internal_vm: # ^0.1.0+1
    path: ../_firebase_internal_vm
  hive: ^2.0.4
  rxdart: ^0.27.2
